// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import frc.robot.commands.C_Roll;

public class OI {
    //// CREATING BUTTONS
    public static final int GAMEPAD_0 = 0;

    public static final int L_STICK_X_AXIS = 0;
    public static final int L_STICK_Y_AXIS = 1;
    public static final int R_STICK_X_AXIS = 4;
    public static final int R_STICK_Y_AXIS = 5;

    public static final int L_TRIGGER = 2;
    public static final int R_TRIGGER = 3;
  
    public static final int BUTTON_A = 1;
    public static final int BUTTON_B = 2;
    public static final int BUTTON_Y = 3;
    public static final int BUTTON_X = 4;

    public static final int L_BUMPER = 5;
    public static final int R_BUMPER = 6;
    
    public static final int BUTTON_BACK = 7;
    public static final int BUTTON_START = 8;

    public static final int L_JOYCLICK = 9;
    public static final int R_JOYCLICK = 10;

    public Joystick driveController = new Joystick(GAMEPAD_0);
    public JoystickButton r_Bumper = new JoystickButton(driveController, R_BUMPER);
    public JoystickButton l_Bumper = new JoystickButton(driveController, L_BUMPER);
    public JoystickButton back_Button = new JoystickButton(driveController, BUTTON_BACK);
    
    public OI() {
        l_Bumper.whenPressed(new C_Roll());
        //r_Bumper.whenPressed(new C_Roll(0.5));
        //back_Button.whenPressed(new C_Roll(stop));
    }
}


